### ISSUE TITLE
SSG_LUGIA works with Fragmented Genomes?

### ISSUE THREAD

**Issue by Fgontr** [nibtehaz/SSG-LUGIA#3]
Hello again!

I have tried to run SSG_LUGIA with fragmented genomes and it gives me the following error.

>>> SSG_LUGIA('/xxxxxx/Software/SSG-LUGIA/codes/sample_data/genome_fragmented.fasta', model_name='SSG-LUGIA-F') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datos1/xxxxx/Software/SSG-LUGIA/codes/main.py", line 30, in SSG_LUGIA
    genome = loadGenome(sequence_fasta_file_path)
  File "/datos1/xxxxx/Software/SSG-LUGIA/codes/file_handling.py", line 18, in loadGenome
    genome = SeqIO.read(file_path,'fasta')
  File "/home/xxxxx/anaconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 754, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle

With complete genomes it works perfectly, I imagine that the fragmented ones don't work but anyway I wanted to ask 

Thanks for your time and patience!

**Comment by nibtehaz** [comment]
Hello, apologies for the late reply.

Yes, the current code isn't designed for fragmented genomes. Please merge the fragments together and then run the algoriithm
